from enum import StrEnum


class EventType(StrEnum):
    """The initial domain event catalog.

    Event names are a typed vocabulary, never string literals scattered through
    the code. Adding a type means adding a payload schema next to it.
    """

    USER_PROFILE_UPDATED = "USER_PROFILE_UPDATED"

    GOAL_CREATED = "GOAL_CREATED"
    GOAL_UPDATED = "GOAL_UPDATED"
    GOAL_PROGRESS_UPDATED = "GOAL_PROGRESS_UPDATED"

    COMMITMENT_CAPTURED = "COMMITMENT_CAPTURED"
    COMMITMENT_UPDATED = "COMMITMENT_UPDATED"
    COMMITMENT_COMPLETED = "COMMITMENT_COMPLETED"

    TASK_CREATED = "TASK_CREATED"
    TASK_COMPLETED = "TASK_COMPLETED"

    DEADLINE_CREATED = "DEADLINE_CREATED"
    DEADLINE_APPROACHING = "DEADLINE_APPROACHING"
    DEADLINE_MISSED = "DEADLINE_MISSED"

    EVENT_CREATED = "EVENT_CREATED"
    EVENT_UPDATED = "EVENT_UPDATED"
    EVENT_CANCELLED = "EVENT_CANCELLED"

    CALENDAR_CONFLICT_DETECTED = "CALENDAR_CONFLICT_DETECTED"
    SOURCE_CONFLICT_DETECTED = "SOURCE_CONFLICT_DETECTED"

    REQUIREMENT_CREATED = "REQUIREMENT_CREATED"
    REQUIREMENT_STATUS_CHANGED = "REQUIREMENT_STATUS_CHANGED"

    CAPTURE_RECEIVED = "CAPTURE_RECEIVED"
    CAPTURE_PARSED = "CAPTURE_PARSED"
    CAPTURE_ROUTED = "CAPTURE_ROUTED"
    CAPTURE_INVALIDATED = "CAPTURE_INVALIDATED"
    CAPTURE_CORRECTED = "CAPTURE_CORRECTED"

    MEMORY_CREATED = "MEMORY_CREATED"
    MEMORY_UPDATED = "MEMORY_UPDATED"
    MEMORY_INVALIDATED = "MEMORY_INVALIDATED"
    MEMORY_SUPERSEDED = "MEMORY_SUPERSEDED"
    MEMORY_SUPPRESSED = "MEMORY_SUPPRESSED"

    RECOMMENDATION_SURFACED = "RECOMMENDATION_SURFACED"
    RECOMMENDATION_ACCEPTED = "RECOMMENDATION_ACCEPTED"
    RECOMMENDATION_DISMISSED = "RECOMMENDATION_DISMISSED"
    RECOMMENDATION_IGNORED = "RECOMMENDATION_IGNORED"

    PREFERENCE_OBSERVED = "PREFERENCE_OBSERVED"
    BEHAVIOR_PATTERN_UPDATED = "BEHAVIOR_PATTERN_UPDATED"

    PURCHASE_RECORDED = "PURCHASE_RECORDED"
    RETURN_WINDOW_CLOSING = "RETURN_WINDOW_CLOSING"

    PRODUCT_ADDED = "PRODUCT_ADDED"
    PRODUCT_LOW = "PRODUCT_LOW"
    PRODUCT_EXPIRED = "PRODUCT_EXPIRED"

    WARDROBE_ITEM_ADDED = "WARDROBE_ITEM_ADDED"
    WARDROBE_ITEM_STATUS_CHANGED = "WARDROBE_ITEM_STATUS_CHANGED"

    CYCLE_STATE_CHANGED = "CYCLE_STATE_CHANGED"

    MOOD_UPDATED = "MOOD_UPDATED"
    ENERGY_UPDATED = "ENERGY_UPDATED"
    SLEEP_UPDATED = "SLEEP_UPDATED"

    WEATHER_CONTEXT_CHANGED = "WEATHER_CONTEXT_CHANGED"

    RADAR_ITEM_DISCOVERED = "RADAR_ITEM_DISCOVERED"
    RADAR_ITEM_SAVED = "RADAR_ITEM_SAVED"
    RADAR_ITEM_DISMISSED = "RADAR_ITEM_DISMISSED"
    RADAR_ITEM_ACTED_ON = "RADAR_ITEM_ACTED_ON"

    GUARDIAN_CAUTION_RAISED = "GUARDIAN_CAUTION_RAISED"
    GUARDIAN_BLOCKED_ACTION = "GUARDIAN_BLOCKED_ACTION"

    READINESS_PLAN_CREATED = "READINESS_PLAN_CREATED"
    READINESS_PLAN_UPDATED = "READINESS_PLAN_UPDATED"
    READY_CHECK_COMPLETED = "READY_CHECK_COMPLETED"

    OPERATOR_ACTION_PROPOSED = "OPERATOR_ACTION_PROPOSED"
    OPERATOR_ACTION_AUTHORIZED = "OPERATOR_ACTION_AUTHORIZED"
    OPERATOR_ACTION_REJECTED = "OPERATOR_ACTION_REJECTED"
    OPERATOR_ACTION_STARTED = "OPERATOR_ACTION_STARTED"
    OPERATOR_ACTION_SUCCEEDED = "OPERATOR_ACTION_SUCCEEDED"
    OPERATOR_ACTION_FAILED = "OPERATOR_ACTION_FAILED"
    OPERATOR_ACTION_PARTIALLY_SUCCEEDED = "OPERATOR_ACTION_PARTIALLY_SUCCEEDED"
    OPERATOR_ACTION_OUTCOME_UNKNOWN = "OPERATOR_ACTION_OUTCOME_UNKNOWN"
    OPERATOR_ACTION_REVOKED = "OPERATOR_ACTION_REVOKED"
    OPERATOR_ACTION_EXPIRED = "OPERATOR_ACTION_EXPIRED"
    OPERATOR_ACTION_REVERSED = "OPERATOR_ACTION_REVERSED"
    OPERATOR_ACTION_COMPENSATED = "OPERATOR_ACTION_COMPENSATED"

    ORCHESTRATION_STARTED = "ORCHESTRATION_STARTED"
    ORCHESTRATION_COMPLETED = "ORCHESTRATION_COMPLETED"
    ORCHESTRATION_FAILED = "ORCHESTRATION_FAILED"
    ACTION_PLAN_CREATED = "ACTION_PLAN_CREATED"
    AUTHORIZATION_REQUESTED = "AUTHORIZATION_REQUESTED"

    NOTIFICATION_RAISED = "NOTIFICATION_RAISED"
    NOTIFICATION_SUPPRESSED = "NOTIFICATION_SUPPRESSED"
    NOTIFICATION_DISPATCHED = "NOTIFICATION_DISPATCHED"
    NOTIFICATION_DELIVERED = "NOTIFICATION_DELIVERED"
    NOTIFICATION_FAILED = "NOTIFICATION_FAILED"
    NOTIFICATION_OPENED = "NOTIFICATION_OPENED"
