from __future__ import annotations

from enum import StrEnum


class EventType(StrEnum):
    """The initial event catalog. Event names are never written as bare strings."""

    USER_PROFILE_UPDATED = "USER_PROFILE_UPDATED"

    GOAL_CREATED = "GOAL_CREATED"
    GOAL_UPDATED = "GOAL_UPDATED"
    GOAL_PROGRESS_UPDATED = "GOAL_PROGRESS_UPDATED"

    COMMITMENT_CAPTURED = "COMMITMENT_CAPTURED"
    COMMITMENT_UPDATED = "COMMITMENT_UPDATED"
    COMMITMENT_COMPLETED = "COMMITMENT_COMPLETED"

    TASK_CREATED = "TASK_CREATED"
    TASK_COMPLETED = "TASK_COMPLETED"

    DEADLINE_CREATED = "DEADLINE_CREATED"
    DEADLINE_APPROACHING = "DEADLINE_APPROACHING"
    DEADLINE_MISSED = "DEADLINE_MISSED"

    EVENT_CREATED = "EVENT_CREATED"
    EVENT_UPDATED = "EVENT_UPDATED"
    EVENT_CANCELLED = "EVENT_CANCELLED"

    CALENDAR_CONFLICT_DETECTED = "CALENDAR_CONFLICT_DETECTED"

    CAPTURE_RECEIVED = "CAPTURE_RECEIVED"
    CAPTURE_PARSED = "CAPTURE_PARSED"
    CAPTURE_ROUTED = "CAPTURE_ROUTED"

    MEMORY_CREATED = "MEMORY_CREATED"
    MEMORY_UPDATED = "MEMORY_UPDATED"
    MEMORY_INVALIDATED = "MEMORY_INVALIDATED"

    PREFERENCE_OBSERVED = "PREFERENCE_OBSERVED"
    BEHAVIOR_PATTERN_UPDATED = "BEHAVIOR_PATTERN_UPDATED"

    PRODUCT_ADDED = "PRODUCT_ADDED"
    PRODUCT_LOW = "PRODUCT_LOW"
    PRODUCT_EXPIRED = "PRODUCT_EXPIRED"

    WARDROBE_ITEM_ADDED = "WARDROBE_ITEM_ADDED"
    WARDROBE_ITEM_STATUS_CHANGED = "WARDROBE_ITEM_STATUS_CHANGED"

    CYCLE_STATE_CHANGED = "CYCLE_STATE_CHANGED"

    MOOD_UPDATED = "MOOD_UPDATED"
    ENERGY_UPDATED = "ENERGY_UPDATED"
    SLEEP_UPDATED = "SLEEP_UPDATED"

    WEATHER_CONTEXT_CHANGED = "WEATHER_CONTEXT_CHANGED"

    RADAR_ITEM_DISCOVERED = "RADAR_ITEM_DISCOVERED"
    RADAR_ITEM_SAVED = "RADAR_ITEM_SAVED"
    RADAR_ITEM_DISMISSED = "RADAR_ITEM_DISMISSED"
    RADAR_ITEM_ACTED_ON = "RADAR_ITEM_ACTED_ON"

    GUARDIAN_CAUTION_RAISED = "GUARDIAN_CAUTION_RAISED"
    GUARDIAN_BLOCKED_ACTION = "GUARDIAN_BLOCKED_ACTION"

    READINESS_PLAN_CREATED = "READINESS_PLAN_CREATED"
    READINESS_PLAN_UPDATED = "READINESS_PLAN_UPDATED"
    READY_CHECK_COMPLETED = "READY_CHECK_COMPLETED"

    OPERATOR_ACTION_PROPOSED = "OPERATOR_ACTION_PROPOSED"
    OPERATOR_ACTION_AUTHORIZED = "OPERATOR_ACTION_AUTHORIZED"
    OPERATOR_ACTION_REJECTED = "OPERATOR_ACTION_REJECTED"
    OPERATOR_ACTION_STARTED = "OPERATOR_ACTION_STARTED"
    OPERATOR_ACTION_SUCCEEDED = "OPERATOR_ACTION_SUCCEEDED"
    OPERATOR_ACTION_FAILED = "OPERATOR_ACTION_FAILED"
    OPERATOR_ACTION_REVERSED = "OPERATOR_ACTION_REVERSED"
